config/routes.rb
GatasisWeb::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: 'delete'

  resources :frontpages

  get 'industry/:name' => 'industries#show'
  get 'sub_categories/new' => 'sub_categories#new'
  get 'sub_categories/:name' => 'sub_categories#show'

  get 'categories/new' => 'categories#new'
  get 'categories/:name' => 'products#list'

  get 'products/details/:name' => 'products#details'

  resources :industries
  resources :sub_categories
  resources :categories
  
  resources :relation_industries

  resources :products

  root 'static_pages#home'
  get '/products' => 'static_pages#products'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/solutions' => 'static_pages#solutions'
  get '/catalog' => 'static_pages#catalog'
  get '/subcat' => 'static_pages#subcat'
  get '/spec' => 'static_pages#spec'
  get '/services' => 'static_pages#services'

  

end

app/models/industry.rb
class Industry < ActiveRecord::Base
	#structure database
	#id:integer, name:string, description:text, header:string
	#
	#order ascending by id in table
	default_scope -> { order('id asc')}
	has_many :relation_industries
	has_many :products, through: :relation_industries
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :admin_check, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_industry, only: [ :edit, :update, :destroy]
  before_action :set_industry_show, only: [:show]
  # GET /industries
  def index
    @industries = Industry.all
  end

  # GET /industries/1
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  def create
    @industry = Industry.new(industry_params)

    if @industry.save
      redirect_to @industry, notice: 'Industry was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /industries/1
  def update
    if @industry.update(industry_params)
      redirect_to @industry, notice: 'Industry was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /industries/1
  def destroy
    @industry.destroy
    redirect_to industries_url, notice: 'Industry was successfully destroyed.'
  end

  private

    def admin_check
      redirect_to root_url unless signed_in? && current_user.admin?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find_by_id(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_industry_show
      if !params[:name].nil?
        @industry = Industry.find_by_name(params[:name].tr('-',' '))
      else
        @industry = Industry.find_by_id(params[:id])
      end
    end

    # Only allow a trusted parameter "white list" through.
    def industry_params
      params.require(:industry).permit(:name, :header, :description)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= simple_form_for @industry, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :header %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                industries_path, :class => 'btn' %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<%- model_class = Industry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/industries/index.html.erb
<%- model_class = Industry -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:header) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= link_to industry.id, industry_path(industry) %></td>
        <td><%= industry.name %></td>
        <td><%= industry.header %></td>
        <td><%= industry.description %></td>
        <td><%=l industry.created_at %></td>
        <td><%=l industry.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_industry_path(industry), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      industry_path(industry),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_industry_path,
            :class => 'btn btn-primary' %>

app/views/industries/new.html.erb
<%- model_class = Industry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/industries/show.html.erb
<%- model_class = Industry -%>
<% provide(:title, 'Industry Solutions') %>
<div class="row">
  <div class="span2">
    <ul class="nav nav-list">
        <li class="nav-header">Industries & Solutions</li>
        <% Industry.select('id','name').each do |list_industry| %>
        <li <%= "class = active" if current_page?(controller: 'industries', action: 'show', name: list_industry.name.tr(' ','-')) %>><%= link_to list_industry.name, controller: 'industries', action: 'show', name: list_industry.name.tr(' ','-') %></li>
        <% end %>
    </ul>
  </div>
  <div class="span10">
      <ul class="breadcrumb">
          <li>Industries & Solutions <span class="divider">/</span></li>
          <li><%= @industry.name %></li>
      </ul>
      <div class="featurette">
        <%= image_tag("solutions/#{@industry.name.downcase.tr(' ', '-')}-main.jpg", class: 'featurette-image pull-right') %>
        <h2 class="featurette-heading"><%=@industry.name %>. <span class="muted"><%= @industry.header %></span></h2>
        <p class="lead"><%= @industry.description %></p>
      </div>
  </div>
</div>

app/views/industries/show_original.html.erb
<%- model_class = Industry -%>
<% provide(:title, 'Industry Solutions') %>
<div class="row">
  <div class="span2">
    <ul class="nav nav-list">
        <li class="nav-header">Industries & Solutions</li>
        <% Industry.select('id','name').each do |list_industry| %>
        <li <%= "class = active" if current_page?(controller: 'industries', action: 'show', name: list_industry.name.tr(' ','-')) %>><%= link_to list_industry.name, controller: 'industries', action: 'show', name: list_industry.name.tr(' ','-') %></li>
        <% end %>
    </ul>
  </div>
  <div class="span10">
      <ul class="breadcrumb">
          <li>Industries & Solutions <span class="divider">/</span></li>
          <li><%= @industry.name %></li>
      </ul>
      <div class="featurette">
        <%= image_tag("solutions/#{@industry.name.downcase.tr(' ', '-')}-main.jpg", class: 'featurette-image pull-right') %>
        <h2 class="featurette-heading"><%=@industry.name %>. <span class="muted"><%= @industry.header %></span></h2>
        <p class="lead"><%= @industry.description %></p>
      </div>
  </div>
</div>