config/routes.rb
GatasisWeb::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: 'delete'

  resources :frontpages

  get 'industry/:name' => 'industries#show'
  get 'sub_categories/new' => 'sub_categories#new'
  get 'sub_categories/:name' => 'sub_categories#show'

  get 'categories/new' => 'categories#new'
  get 'categories/:name' => 'products#list'

  get 'products/details/:name' => 'products#details'

  resources :industries
  resources :sub_categories
  resources :categories
  
  resources :relation_industries

  resources :products

  root 'static_pages#home'
  get '/products' => 'static_pages#products'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/solutions' => 'static_pages#solutions'
  get '/catalog' => 'static_pages#catalog'
  get '/subcat' => 'static_pages#subcat'
  get '/spec' => 'static_pages#spec'
  get '/services' => 'static_pages#services'

  

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	belongs_to :category
	has_many :products
	#
	# This is for paperclip picture
	has_attached_file :sub_category_picture1, :styles => { :original => "260x260>", :thumb => "100x100>" }, path: "sub_categories/:id/:style/1_:id_:filename",
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :admin_check, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_sub_category, only: [:edit, :update, :destroy]
  before_action :set_sub_category1, only: [:show]
  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sub_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url }
      format.json { head :no_content }
    end
  end

  private

    def admin_check
      redirect_to root_url unless signed_in? && current_user.admin?
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    def set_sub_category1
      @category = Category.find_by_name(params[:name].tr('-',' '))
      @sub_category = @category.sub_categories
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :description, :category_id, :sub_category_picture1)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= simple_form_for @sub_category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %> limit to 100 characters only
  <%= f.association :category, include_blank: t('.select_category') %>
  <%= f.file_field :sub_category_picture1 %> JPEG file, size 260 x 260
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sub_categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_categories/index.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= link_to(image_tag(sub_category.sub_category_picture1.url(:thumb)), sub_category_path(sub_category)) %></td>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.description %></td>
        <td><%= sub_category.category.name %></td>
        <td><%=l sub_category.created_at %></td>
        <td><%=l sub_category.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sub_category_path(sub_category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sub_category_path(sub_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sub_category_path,
            :class => 'btn btn-primary' %>

app/views/sub_categories/new.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_categories/show.html.erb
<% provide(:title, "#{@category.name} | PT GATASIS INDONESIA") %>
<div class="row">
	<div class="span3">
    <%= render 'layouts/side_nav' %>
	</div>
	<div class="span9">
		<ul class="breadcrumb">
          <li>Products <span class="divider">/</span></li>
          <li><%= @category.name %></li>
      	</ul>
      	  <div class="featurette">
          <%= image_tag @category.category_picture1.url, class: 'featurette-image pull-right' %>
    			<h3 class="featurette-heading"><%= @category.name %></h3>
    			<p><%= @category.description %></p>
  		  </div>
        <br>
        <div class="row-fluid">
          <ul class="thumbnails">
            <% @sub_category.each do |list_sub| %>
              <li class="span4">
                <div class="thumbnail">
                  <%= link_to(image_tag(list_sub.sub_category_picture1.url),"/categories/#{list_sub.name.tr(' ','-')}") %>
                  <div class="caption">
                    <h3><%= list_sub.name %></h3>
                    <p><%= list_sub.description %></p>
                  </div>
                </div>
              </li>
              <% end %>
            </ul>
        </div>
	</div>
</div>

app/views/sub_categories/show_edited.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sub_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @sub_category.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @sub_category.category_id %></dd>
</dl>
<%= image_tag @sub_category.sub_category_picture1.url %>
<%= image_tag @sub_category.sub_category_picture1.url(:medium) %>
<%= image_tag @sub_category.sub_category_picture1.url(:thumb) %>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sub_categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sub_category_path(@sub_category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sub_category_path(@sub_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>