config/routes.rb
GatasisWeb::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: 'delete'

  resources :frontpages

  get 'industry/:name' => 'industries#show'
  get 'sub_categories/new' => 'sub_categories#new'
  get 'sub_categories/:name' => 'sub_categories#show'

  get 'categories/new' => 'categories#new'
  get 'categories/:name' => 'products#list'

  get 'products/details/:name' => 'products#details'

  resources :industries
  resources :sub_categories
  resources :categories
  
  resources :relation_industries

  resources :products

  root 'static_pages#home'
  get '/products' => 'static_pages#products'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/solutions' => 'static_pages#solutions'
  get '/catalog' => 'static_pages#catalog'
  get '/subcat' => 'static_pages#subcat'
  get '/spec' => 'static_pages#spec'
  get '/services' => 'static_pages#services'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="container">
	<div class="row">
		<div class="span3">
			<ul>
				<li>Industries & Solutions
                  <ul>
                    <% Industry.select('id','name').each do |list_industry| %>
                        <li><%= link_to list_industry.name, controller: 'industries', action: 'show', name: list_industry.name.tr(' ', '-') %></li>
                    <% end %>
                  </ul>
				</li>
			</ul>
		</div>
		<div class="span3">
			<ul>
				<li>Products
                  <ul>
                    <% Category.select('id','name').each do |list_category| %>
                        <li><%= link_to list_category.name, controller: 'sub_categories', action: 'show', name: list_category.name.tr(' ', '-') %></li>
                    <% end %>
                  </ul>
				</li>
				<li><%= link_to "Services & Support",''%></li>
			</ul>
		</div>
		<div class="span3">
			<ul>
				<li><%= link_to "About us",''%></li>
				<li><%= link_to "Find our location",''%></li>
				<li><%= link_to "Resources",''%>
					<ul>
						<li><%= link_to "Sitemap",''%></li>
					</ul>
				</li>
			</ul>
		</div>
		<div class="span3">
			<div class="contact">
				<h4>Need help? Call us at:<br>+6221-6682592</h4><br>
				E-mail: sales@ptgatasisindonesia.com
			</div>
		</div>
	</div>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
    <div class="masthead">
        
        <h3 class="muted">PT GATASIS INDONESIA</h3>
    </div>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="text-navbar">MENU</span>
            <% if signed_in? %>
              <%= link_to 'Hi, '+ current_user.name, signout_path, method: "delete", class: 'login-navbar' %>
            <% else %>
              <%= link_to 'Sign in', signin_path, class: 'login-navbar' %>
            <% end %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'home') %>><%= link_to "Home", root_path %></li>
              <li class="dropdown <%= "active" if params[:controller]=='industries' %>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Industries & Solutions</a>
                  <ul class="dropdown-menu">
                    <% Industry.select('id','name').each do |list_industry| %>
                        <li><%= link_to list_industry.name, controller: 'industries', action: 'show', name: list_industry.name.tr(' ', '-') %></li>
                    <% end %>
                  </ul>
              </li>
              <li class="dropdown <%= "active" if params[:controller]=='products' %>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products</a>
                  <ul class="dropdown-menu">
                    <% Category.select('id','name').each do |list_category| %>
                        <li><%= link_to list_category.name, controller: 'sub_categories', action: 'show', name: list_category.name.tr(' ', '-') %></li>
                    <% end %>
                  </ul>
              </li>
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'services') %>><%= link_to "Service & Support", services_path %></li>
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'about') %>><%= link_to "About Us", about_path %></li>
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'contact') %>><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div><!-- end navbar -->   
</div>

app/views/layouts/_header_edited.html.erb
<div class="container">
    <div class="masthead">
        <h3 class="muted">PT GATASIS INDONESIA</h3>
    </div>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
            <ul class="nav">
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'home') %>><%= link_to "Home", home_path %></li>
              <li class="dropdown <%= "active" if params[:controller]=='industries' %>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Industries & Solutions</a>
                  <ul class="dropdown-menu">
                    <% Industry.select('id','name').each do |list_industry| %>
                        <li><%= link_to list_industry.name, controller: 'industries', action: 'show', name: list_industry.name.tr(' ', '-') %></li>
                    <% end %>
                  </ul>
              </li>
              <li class="dropdown <%= "active" if params[:controller]=='products' %>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products</a>
                  <ul class="dropdown-menu">
                    <% Category.select('id','name').each do |list_category| %>
                        <li><%= link_to list_category.name, controller: 'sub_categories', action: 'show', name: list_category.name.tr(' ', '-') %></li>
                    <% end %>
                  </ul>
              </li>
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'services') %>><%= link_to "Service & Support", services_path %></li>
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'about') %>><%= link_to "About Us", about_path %></li>
              <li <%= "class = active" if current_page?(controller: 'static_pages', action: 'contact') %>><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div><!-- end navbar -->   
</div>

app/views/layouts/_side_nav.html.erb
<div class="accordion" id="accordion2">
  <% a = 0 %>
  <% Category.select('id','name').each do |list_category| %>
  <% a = a + 1 %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" href="#collapse<%= a %> ">
        <%= list_category.name %>
      </a>
    </div>
    <div id="collapse<%= a %>" class="accordion-body collapse <%= 
    if params[:name].tr('-',' ') == list_category.name
        "in"
     elsif !SubCategory.find_by_name(params[:name].tr('-',' ')).nil?
        if SubCategory.find_by_name(params[:name].tr('-',' ')).category.name  == list_category.name
            "in"
        end
      elsif !Product.find_by_name(params[:name].tr('_',' ')).nil?
        if Product.find_by_name(params[:name].tr('_',' ')).sub_category.category.name == list_category.name
          "in"
        end
     end  %>">
      <div class="accordion-inner">
        <ul>
          <% SubCategory.where(category_id: list_category.id).each do |list_sub_category| %>
        	<li><%= list_sub_category.name %>
            <ul class="nav nav-list">
                <% Product.where(sub_category_id: list_sub_category.id).each do |list_product| %>
                <li <%= "class=active" if list_product.name == params[:name].tr('_',' ') %>><%= link_to list_product.name, "/products/details/#{list_product.name.tr(' ','_')}" %></li>
                <% end %>
            </ul>
          </li>
        	<% end %>
        </ul>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GatasisWeb" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "defaults" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="fb-root"></div>
      <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
              }(document, 'script', 'facebook-jssdk'));</script>
  <%= render 'layouts/header' %>
    <div class="container-fluid">
        <div class="container">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
    </div> <!-- /container -->
  </body>
</html>